version: '3'
services:
  #nginx
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #Django
  app:
    image: django:latest
    